### ISSUE TITLE
Redo UI

### ISSUE THREAD

**Issue by johrstrom** [johrstrom/jmeter-prometheus-plugin#10]
If we keep going at this rate, we'll overload that dialogue box.  I modelled it after the Simple Data Writer, but maybe it's becoming apparent that there are many configurations that would be better just in the main ui instead.

**Comment by johrstrom** [comment]
I've started working on [this branch](https://github.com/johrstrom/jmeter-prometheus-plugin/tree/refactor-ui).  It is essentially going to wipe the Save dialogue in favour of a bunch of panels like most other jmeter gui elements. 

As a design question, now is a good time to decide if we want to continue with the PrometheuSaveConfig class as an abstraction for configurations or if we simply want to access each one by TestElement.getProperty("name_of_property").  

Or as a third option that PrometheusSaveConfig class would actually be backed up by the JMeterProperty infrastructure - which may actually be the route to go because then the classes currently using it don't have to change. 

I could go either way.

**Comment by GiovanniPaoloGibilisco** [comment]
I think that the third option is the more flexible. 
I used local variables to the listener class ( e.g. collectSamples ) to control sample gathering when one of the collector is not active. Probably we should abandon these varibales and use appropriate methods from the PrometheuSaveConfig class.

**Comment by chiabre** [comment]
I notice that right that collector gathers metrics from any sampler, even those not generating request (eg. beanshell sampler,timer, etc..). This may be misleading when looking that total requests count. 
It would be nice to be able to configure the sampler to monitor.

**Comment by johrstrom** [comment]
I agree, I opened [this issue](https://github.com/johrstrom/jmeter-prometheus-plugin/issues/13) for that.  I can't get it in this re-factor, but after for sure.

**Comment by johrstrom** [comment]
I'm closing this because we pulled in this re-factor quite some time ago.
