### ISSUE TITLE
Is there a way to compare Historical response times?.

### ISSUE THREAD

**Issue by ezhilnarasu** [johrstrom/jmeter-prometheus-plugin#100]
Can anyone help me in configuring historical response times in Grafana?.

**Comment by johrstrom** [comment]
I quickly searched grafana for an issue, then got side tracked. But in any case - whether you can or not, Grafana is the place to search for the topic. I _believe_ you can timeshift a query somehow (maybe in Prometheus?) but I don't know it for a fact or recall it.

Not trying to close the ticket to be mean, and I do appreciate you opening it, but I just don't have the to investigate it.
