### ISSUE TITLE
Q: Instructions on how to execute load test on Distributed Jmeter?(with Prometheus)

### ISSUE THREAD

**Issue by jayadeepGit** [johrstrom/jmeter-prometheus-plugin#102]
Hi,

I tried to find docs on how to execute the jmeter load test(in a distributed Environment ) where the metrics are exposed on the IP instead of localhost. Also, any pre-requisites that are applicable.

Note: I got everything working on a standalone instance(Thanks for the Readme)

**Comment by johrstrom** [comment]
It should work the same, only the metrics are available on the workers IPs, not the masters'.
