### ISSUE TITLE
Prometheus is not able to capture jmeter stats from slave machines

### ISSUE THREAD

**Issue by Sravanthi0614** [johrstrom/jmeter-prometheus-plugin#111]
HI ,

I have integrated jmeter and prometheus using plugin jar 0.6.0 . During the test, jmeter summary file is capturing all the stats from the master and slave machine in master machine but prometheus is capturing the stats only from jmeter master. Added Prometheus Listener.
I have configured the Jmeter-prometheus plugin in Master and slave machines and all the machines have Jmeter version 5.4.1 and jmeter-prometheus-plugin-0.6.0.jar

Kindly let me know how to get the jmeter stats from slave machines on prometheus.

**Comment by johrstrom** [comment]
Be sure to have prometheus scrape from all the minion instances too.  You may have it only set to scrape the main instance.

**Comment by Sravanthi0614** [comment]
Working as expected after configuring in slave machines
