### ISSUE TITLE
Client/Server instantion kerfuffle

### ISSUE THREAD

**Issue by GiovanniPaoloGibilisco** [johrstrom/jmeter-prometheus-plugin#14]
One of the pain points in running a Jmeter test in distributed mode is the collection of results on the Client instance controlling the test. Jmeter implements this feature in different ways, from syncronous forwarding of the response to batch forwarding of statistics data. 

It would be very useful being able to launch the exporter on all the Jmeter Server instances in order to allow scaping directly from the injectors. 
This also allows to brake down events by injector.

**Comment by GiovanniPaoloGibilisco** [comment]
Adding some info, 
When a test is launched in a distributed environment with n "servers" Jmeter starts n exporters and servers, one for each "server". This causes n-1 exceptions on the http listening port of the exporter already being used by the 1 exporter that has been succesfully launched. I see 2 roads ahead here. 
1) Using a single http exporter by implementing the factory pattern. 
2) Being able to launch exporters directly on "server" instances and configure prom to scrape from them. This also offloads jmeter from gathering results.

**Comment by chiabre** [comment]
A benefit of the second option is that it will give us for free the possibility to "slice and dice" the data also from the "server" perspective.  This could be really usefull to:
1. keep track of the differences when a test is executed from different (geo)location
2. spot anomalies in the test farm 

Having the same through the first option could result in overlabeling...

**Comment by johrstrom** [comment]
In researching this issue it seems I implemented [Remoteable](https://jmeter.apache.org/api/org/apache/jmeter/samplers/Remoteable.html) which forced only one instantiation on the client. 

It was a mistake, so really this is a bug, we should definitely instantiate on the servers.

**Comment by johrstrom** [comment]
I changed this to a bug because that's what I believe it now to be.  I had always intended the server to boot on the server and never send data back to the client. 

As I started to create a pull request for a fix branch I noticed you have a branch for BackendClient. Reading the [documentation](https://jmeter.apache.org/api/org/apache/jmeter/visualizers/backend/BackendListenerClient.html) for the interface it says it creates 1 per thread and perhaps more.  I think just relying on [NoThreadClone](https://jmeter.apache.org/api/org/apache/jmeter/engine/util/NoThreadClone.html) is a better approach.  

I'm creating the pull request now and we can either continue to discuss it here, or there. It does revert the factory pattern @GiovanniPaoloGibilisco  had implemented. I'm in no rush to pull it in quickly.

**Comment by GiovanniPaoloGibilisco** [comment]
From the jmeter developer mail list I was suggested to look at the BackendListenerClient implementation of InfluxDB and Graphite exporters. [This branch](https://github.com/johrstrom/jmeter-prometheus-plugin/tree/backend-listener) implements the exporter as a BackendListenerClient but still this relies on the fact that the Client receives samples from the servers. I've also inspected the idea of extending the [BackendListener](https://jmeter.apache.org/api/org/apache/jmeter/visualizers/backend/BackendListener.html) but this is definetly not the way to go.

**Comment by johrstrom** [comment]
Oh I see. With the NoThreadClone or the singleton you had implemented you still boot 1 server per JVM.  But, if you're trying to boot multiple servers (JVM/processes) on one single instance (machine) you'll still get port binding errors in either case.  

Is that what you were trying to do? If so, you may want to try to use the __Random function and bind to a random port. Of course that doesn't make auto discovery easy, but ideally Jmeter servers and host servers should be 1:1.

**Comment by GiovanniPaoloGibilisco** [comment]
No, I was trying to avoid running multiple http servers inside the JVM with the Jmeter Client. This was a temporary fix due to the fact that multiple instances of the exporter were running on the client instead of running on the server. I would prefer to stick with the default 9270 port and allowing customization.
