### ISSUE TITLE
compile issue

### ISSUE THREAD

**Issue by ravcoder143** [johrstrom/jmeter-prometheus-plugin#26]
Below lib is not available after importing pom.xml.

import org.apache.jmeter.assertions.AssertionResult;
import org.apache.jmeter.engine.util.NoThreadClone;
import org.apache.jmeter.reporters.AbstractListenerElement;

**Comment by johrstrom** [comment]
The maven dependency is "provided" for the jmeter core jar. Are you having this issue running mvn package or compiling in your ide?  Or trying to import this pom into some other project?

**Comment by johrstrom** [comment]
I'm closing this as I'm not sure what the problem was, or is but it doesn't seem to affect anyone else.
