### ISSUE TITLE
Prometheus Listener Server / Port ?

### ISSUE THREAD

**Issue by jricardooliveira** [johrstrom/jmeter-prometheus-plugin#27]
Hi,

The listener gui interface does not allow to specify an IP / port. What should I do when prometheus is not on the same server as jmeter?

Regards
Joao

**Comment by johrstrom** [comment]
Master branch definitely does have the GUI text field to specify port. The ip is the ip of whatever machine you happen to be running the jvm on. 

If you happen to be using the updates branch, then you need to use the as of yet undocumented property **prometheus.port** but I'm still working on this branch from time to time so I haven't quite figured out what's appropriate in terms of settings.

**Comment by jricardooliveira** [comment]
So it will be prometheus that will connect to this port to read the exported data right ?
How do I setup prometheus to read from my host/port ?

**Comment by johrstrom** [comment]
If you boot them both locally, I believe this config should work. Given that you've configured jmeter to use port 9270. If you're trying to do it remotely then you'll have to replace localhost with whatever ip jmeter is running on. 

Note that this is just scrape_configs, it's not the full config file you'll need.
```
scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090', 'localhost:9270']
       
```

**Comment by johrstrom** [comment]
I'm going to close this as I believe you've probably figured this out by now.  Please feel free to open another issue should you have more questions.
