### ISSUE TITLE
Could not find Prometheus Listener in Jmeter

### ISSUE THREAD

**Issue by nirmalraj-sn** [johrstrom/jmeter-prometheus-plugin#28]
Could not find Prometheus Listener in Jmeter.
Maven build successful, placed the created shaded and original jar in $Jmeter_Home\lib.
Started the Jmeter application, checked for Listener, but could not find it.
No error logs in Jmeter application.

Environment :
Win 10 Enterprise, 64bit
java version "1.8.0_151"
Apache Jmeter 4.0 and Apache 3.3

**Comment by johrstrom** [comment]
The README erroneously says to move to the $JMETER_HOME/lib/ folder. You should actually move to the $JMETER_HOME/lib/ext folder.  I've updated the docs for the same.
