### ISSUE TITLE
Question: How to add custom labels?

### ISSUE THREAD

**Issue by JuanEtcheverry** [johrstrom/jmeter-prometheus-plugin#29]
Hi @johrstrom,

I'm currently working on a project using this plugin. Since there isn't much documentation on this that I can find. Can you explain me how to add custom labels?

Thanks

**Comment by johrstrom** [comment]
You can use sample variables at the moment. Itll inheret whatever youve configured jmeter to use.

Also im working on a 0.1.0 version thats going to be alot more flexible.



Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by JuanEtcheverry** [comment]
Thanks for your help! Save my life! :)
