### ISSUE TITLE
Use Sample Variables

### ISSUE THREAD

**Issue by johrstrom** [johrstrom/jmeter-prometheus-plugin#3]
Jmeter allows for sample_variables to be populated and used in the SimpleWriter listener class.  We should also use this feature for labeling.

**Comment by steinwelberg** [comment]
Hi Jeff, we are willing to contribute this feature to this project. Are there any things that we should take into consideration? (Since the project doesn't have any contribution guide or any guidelines we should follow ;).

**Comment by johrstrom** [comment]
Hi, sorry I haven't implemented this yet I got side tracked by a different shiny object. I can fulfil this tonight when I get home or you can submit the PR directly.  My only guideline would to be reasonable. I tend to follow basic Java coding standards as well as any Jmeter standards. But this specifically should be pretty straight forward especially as, when I wrote it, I meant to basically just copy paste how the SimpleDataWriter does it.

**Comment by johrstrom** [comment]
I went to make the PR for you and others to review, turned out I accidentally committed directly to master in this [commit](https://github.com/johrstrom/jmeter-prometheus-plugin/commit/88dfdbd006a2420d858d24a5850ce92bb4dee1b0).  Can you confirm that works as you expect it to? After I close this I think I may try to tag so ppl can grab current functionality off of Maven central.

**Comment by steinwelberg** [comment]
No problem good to hear that it is already implemented :)
We can have a look in about 2 weeks. 

I'll keep you informed!

**Comment by johrstrom** [comment]
I just found and fixed a bug where this wouldn't update if sample variables are null, i.e,, they're from an extractor that didn't extract anything or they're extracted at a later point in the test plan. 

In any case, I feel this feature to be done, if you need me to reopen I can do so.
