### ISSUE TITLE
No .jar file released

### ISSUE THREAD

**Issue by allangood** [johrstrom/jmeter-prometheus-plugin#31]
Hi, first of all, thank you for your work!
Do you thing it is possible to release the final .JAR file in the "Release" section?
This will make a life of a non developer a little bit easy! :)

Regards.

**Comment by johrstrom** [comment]
Thanks. I really should do that. Ive been meaning to put it on maven central, but this may actually be better.



Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by johrstrom** [comment]
Thanks again for this ticket, but I've started to publish jars on this repo now.  Please check out the new version!
