### ISSUE TITLE
All metrics are not exposed

### ISSUE THREAD

**Issue by rohitshrivastva** [johrstrom/jmeter-prometheus-plugin#33]
Hi,
I am getting only one metrics -
jmeter_running_threads 2.0

No other metrics are exposed.

**Comment by johrstrom** [comment]
Be sure the listener is in the correct/expected scope.

You can attach the testplan (removing whatever sensitive/proprietary data) here and i can take a look.



Sent via the Samsung Galaxy S7 edge, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by var23rav** [comment]
@rohitshrivastva Make sure you have selected the label from GUI.

![image](https://user-images.githubusercontent.com/7958115/45684395-cb31e000-bb63-11e8-917c-92aee90a42e9.png)

**Comment by johrstrom** [comment]
I'm hoping this answered your question.  Please re-open or open another ticket if you have more questions.
