### ISSUE TITLE
Number of JMeter Threads Are Not Correctly Logged

### ISSUE THREAD

**Issue by singhpawankumar** [johrstrom/jmeter-prometheus-plugin#34]
Hi,
I did the configuration to monitor using prometheus listener in JMeter 3.2 and monitored it on Grafana Dashboard. During testing I noticed not all threads are getting logged in the dashboard.

For, e.g. if I have to 2 JMeter thread groups in the JMX script. First Thread Group is running with 5 threads and second thread Group is running with 10 threads. While monitoring in Grafana, I noticed the Number of running threads is always shows 10 instead of 15. If I interchange the number of threads in the script, it shows 5 threads only.

Please provide your fix if it's an issue.

Regards,
Pawan Singh

**Comment by johrstrom** [comment]
Yes, looking at the code here it appears that it's thread group specific. Unfortunately right now, you can't have more than 1 listener per test plan unless you have a different server (port) entirely, but that likely doesn't work at all. 

Thank you for the issue. It is a bug that I will take care of.

https://github.com/johrstrom/jmeter-prometheus-plugin/blob/master/src/main/java/com/github/johrstrom/listener/PrometheusListener.java#L127

**Comment by johrstrom** [comment]
This issue is resolved in the newest versions. It looks like this. Please check it out. It's not backwards compatible, but it will be forward compatible. 

![image](https://user-images.githubusercontent.com/4874123/52388325-b8e90d80-2a42-11e9-8f52-be5714968333.png)

I'm going to close this ticket, and open a similar one to also populate a thread group label, but that's an enhancement.  Thanks again for the ticket.

**Comment by antplant** [comment]
@johrstrom did you ever get further with this? I have a test plan with multiple arrival-based thread groups and I'd like to monitor the level of concurrency on a per-threadgroup basis, which doesn't seem to be possible currently.

**Comment by johrstrom** [comment]
Looks like not, _and_ I never opened a second ticket! I've done so in #66. I apologize for doing half of this then saying I'd open the ticket, and not doing that, and then forgetting about it forever.

Thanks for the reminder! I'll try to get around to it this week.

**Comment by antplant** [comment]
Awesome cheers - in the meantime I've worked around this with a custom metric and some pre/postprocessors to keep track of thread counts. Definitely would be good to have it built in though!
