### ISSUE TITLE
loss of data points at the very end of tests

### ISSUE THREAD

**Issue by johrstrom** [johrstrom/jmeter-prometheus-plugin#39]
Let's imagine a jmeter test with this plugin(s) is running and it ends at 1:00:00.  The prometheus server that is scraping this particular JVM (jmeter instance) is in a cycle such that it'll scrape at 12:59:35 and  1:00:05 (30 second scrape interval). 

That leaves roughly 25 seconds of uncollected metrics because the test ends calls this plugins' testEnded function which stops the http server. Now, that may or may not be negligible in a performance test which can run for an hour or more, but it has to at least be documented as a known issue.

**Comment by johrstrom** [comment]
As a workaround to this problem (and perhaps the only solution) is to add a sufficient value in the `prometheus.delay` property. So that if you where to set to this to say 30, when jmeter stops the test, this library will block for 30 seconds so that the prometheus server may scrape it one last time.

**Comment by johrstrom** [comment]
I don't believe this problem can be solved in a simpler way than described above, so I'm closing this ticket. It is, at least for now, documentation that this project has considered this boundary condition.

**Comment by jyoprakashJP** [comment]
I tried putting 30 sec or more to the prometheus.delay property, but as soon as  Jmeter test stop, metrics http server is down immediately. how to resolve this?
