### ISSUE TITLE
Configurable collector type for assertions

### ISSUE THREAD

**Issue by GiovanniPaoloGibilisco** [johrstrom/jmeter-prometheus-plugin#5]
I would like to make the type of collector for assetions configurable. 

In my use case I'm interested in separating the time taken to respond to requests according to the outcome of the assertion. 

e.g. In my (JSON) response  there is a "fallback" field, I would like to be able to separate the time taken to serve request when "fallback" is true and false. Using just volumes this is not possible because the sampler collector aggregates both of them. 

Another option would be adding the assertion value as a label to the sample collector but since multiple assertions can be defined for each sampler the number of labels could easily explode.

**Comment by johrstrom** [comment]
I didn't realize you had a use case in mind.  I have another issue to refactor the UI, perhaps we could catch this issue in that branch.

**Comment by johrstrom** [comment]
This just got fixed in #16 right? Are you ok to close?

**Comment by GiovanniPaoloGibilisco** [comment]
Yes, fixed and working. 
Closing.
