### ISSUE TITLE
Deploy to mvn repository

### ISSUE THREAD

**Issue by pelletier2017** [johrstrom/jmeter-prometheus-plugin#56]
Could you upload the releases to a remote mvn repo such as `https://mvnrepository.com` to easily download at build time?

**Comment by johrstrom** [comment]
I've looked into it before, but it just seemed too daunting. Looking at it now, I feel more comfortable doing so, so yea! I can push it somewhere.

**Comment by johrstrom** [comment]
Sorry, don't know why I closed this, maybe I'd meant to give it a label?  Either way, I am going to do this, so closing it was an accident.

(I may have just clicked the wrong button when I commented)

**Comment by johrstrom** [comment]
Done. Version 0.5.0 and beyond will be deployed to oss.sonatype.org.  You can see information in the [README here](https://github.com/johrstrom/jmeter-prometheus-plugin#download). 

Thanks again for opening the ticket!
