### ISSUE TITLE
Add response_code and response_message metrics

### ISSUE THREAD

**Issue by OlegKashtanov** [johrstrom/jmeter-prometheus-plugin#59]
Hi!
On influx backend listener  "responseMessage", "responseCode" fields are available.
And responseMessage is used when we have a error response.
They are very useful in grafana table view like that:
![image](https://user-images.githubusercontent.com/8101276/63518176-23522e80-c4f9-11e9-830f-fbbe2d18e4fd.png).
Is it possible to add that kind of metrics?

**Comment by johrstrom** [comment]
Response code for sure, See the README for `code is a keyword. It's the response code of the result.`

I don't think response message is really appropriate though. Remember these are prometheus metrics and we're not supposed to have labels with super high cardinality, like response messages.

**Comment by johrstrom** [comment]
That said, take a look a the README again - specifically [this bit](https://github.com/johrstrom/jmeter-prometheus-plugin#using-jmeter-variables-as-labels) about creating arbitrary labels from variables.  

If you where able extract the response message from jmeter, maybe through a JSR223 PostProcessor and put it into a variable, called, say `response_message` - then add `response_message` to the `labels` of a given metric, then you would be collecting the response message. 

Again, this is not recommended, so you may want to check in the JSR223 post processor if the response size is less than so much or if it starts with 'Not HTTP response', etc then you add it, if not you just assign an empty string. 

Response codes should work out of the box with the `code`, and should even capture codes like that exception message you have shown.

**Comment by OlegKashtanov** [comment]
Thanks. It works for me.
