### ISSUE TITLE
NonGUI mode: The JVM should have exited but did not

### ISSUE THREAD

**Issue by OlegKashtanov** [johrstrom/jmeter-prometheus-plugin#61]
**Version 0.5.0**
After test i have:

```summary =   1199 in 00:02:01 =    9.9/s Avg:     7 Min:     4 Max:   191 Err:     0 (0.00%)
Tidying up ...    @ Tue Aug 27 18:16:35 MSK 2019 (1566918995756)
... end of run
The JVM should have exited but did not.
The following non-daemon threads are still running (DestroyJavaVM is OK):
Thread[pool-2-thread-1,5,main], stackTrace:sun.misc.Unsafe#park
java.util.concurrent.locks.LockSupport#park
java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject#await
java.util.concurrent.LinkedBlockingQueue#take
java.util.concurrent.ThreadPoolExecutor#getTask
java.util.concurrent.ThreadPoolExecutor#runWorker
java.util.concurrent.ThreadPoolExecutor$Worker#run
java.lang.Thread#run

Thread[DestroyJavaVM,5,main], stackTrace:
```
**Workaround**: set jmeterengine.stopfail.system.exit=true

If i stop to send pull requests from prometheus to jmeter-exporter - all fine (of course, without metrics in prometheus).

[threaddump-1566919071184.txt](https://github.com/johrstrom/jmeter-prometheus-plugin/files/3546941/threaddump-1566919071184.txt)

**Comment by OlegKashtanov** [comment]
I mean that threads are locked only when prometheus server send requests to http://jmeter_host:9270/metrics.
If we don't mute prometheus listener in test plan and stop prometheus server then problem is not reproduced.

**Comment by GiovanniPaoloGibilisco** [comment]
#63 should fix this. 
Tested in an automated environment about 20 times every shutdown was clean. It's hard to reproduce this behavior in CI tests.

**Comment by OlegKashtanov** [comment]
**Env**:
Jmeter 5.1.1
jmeter-prometheus-plugin from [fix-termination](https://github.com/johrstrom/jmeter-prometheus-plugin/tree/fix-termination)
**Retest**:
Check on standalone and distributed Jmeter mode.
Result:
All works fine.

**Comment by GiovanniPaoloGibilisco** [comment]
As #63 is not yet merged I would keep the issue open.

**Comment by johrstrom** [comment]
Thanks all, I'll close this tonight when I'm able to release 0.5.1.

**Comment by johrstrom** [comment]
This is in 0.5.1 release. Thanks @GiovanniPaoloGibilisco for the PR.
