### ISSUE TITLE
HTTP Sampler Metrics

### ISSUE THREAD

**Issue by rnavarette** [johrstrom/jmeter-prometheus-plugin#64]
Hello,

Sorry if this question is too simple, but we're having a really tough time accessing what we hope we'd see when attaching a listener to an HTTP sampler.  The only jmeter_ metric that appears in the scrape request is the number of client threads, but none of the "standard" metrics like response time average, min, max, etc.

Do we need to define each of these to be output individually?  If we need to add them to the table in the GUI, is there any "standard" or "automatic" variables available for this sampler?  Or, do we need to copy all of the HTTP metrics we'd want into "custom" metrics?

Hopefully this question makes sense... I'm hoping someone has encountered this before and we're not the only people wanting the "standard" response metrics from an HTTP request :)

thanks much

**Comment by johrstrom** [comment]
Hi! No need to be sorry and, yes your question does make sense. 

You do currently have to define all of these individually. Though, you raise a good point - maybe the library should just initialize with some defaults. 

This plugin started out that way, but it was _too_ restrictive, folks couldn't define anything, they got whatever metrics we gave them out of the box. Now we've got it setup to where it's maybe a little _too_ user defined? 

The idea was I didn't want to set policy on what your metric names should be or what you want to collect, but maybe there's a middle ground where the listener can initialize with some settings.

**Comment by johrstrom** [comment]
I've created #65 as an enhancement that gives you the behaviour your looking for.

Let me know if that answers your question or is what you were looking for.  Thanks for the ticket!

**Comment by rnavarette** [comment]
Yup, thats the idea exactly.  In an ideal world, you could (easily) add the built-in metrics to the metrics table - or, perhaps they're automatically added when you apply the plugin and could delete them.

Ok, so, adding them ourselves shouldn't be too terrible (i think) but, is there any documentation on what we'd fill in for each of those options?  Or, do we need to write the manual sample code to fill in each of the prometheus counters manually based on what JMeter makes available in its API?

thanks again

**Comment by johrstrom** [comment]
> Or, do we need to write the manual sample code

Not sure what you mean here, you shouldn't have to write code, especially if you just want some defaults like response time.

The README has lots of examples, especially [here](https://github.com/johrstrom/jmeter-prometheus-plugin#listener-quickdoc) in the image at a glance it shows a lot.  The README also has stuff about what all the columns mean/do.  

There's also an example JMX [here](https://github.com/johrstrom/jmeter-prometheus-plugin/blob/master/docs/examples/simple_prometheus_example.jmx) to get you started if you just want to pull it and copy the listener.

**Comment by johrstrom** [comment]
I'm going to close this because I've opened the other ticket (#65) for the actual implementation. Thanks for opening the ticket!
