### ISSUE TITLE
Ability to specify IP / bind address?

### ISSUE THREAD

**Issue by java-javascript** [johrstrom/jmeter-prometheus-plugin#68]
Thanks for the project Jeff - nice work.

Is it possible to assign the bind address (0.0.0.0 or IP address) so that metrics are served by an externally accessible address (rather than the default 127.0.0.1 / localhost)?  If this is not currently possible, are there plans to add this enhancement?

Use cases related to the question:
- Ability to run JMeter on one machine but access metrics via Prometheus from another.
- Ability to run JMeter on a host machine with Prometheus running on a docker image on the host machine

In each case, localhost/127.0.0.1 is not usable.

I think there is an interest in this functionality from others as it is referenced in passing in previously closed issues:
- https://github.com/johrstrom/jmeter-prometheus-plugin/issues/27
- https://github.com/johrstrom/jmeter-prometheus-plugin/issues/32

**Comment by johrstrom** [comment]
Hi! Thanks for the ticket, and for the referenced tickets.   Especially #32, unfortunately it looked like that person needed to bind to 0.0.0.0 and at the time I didn't know it (I've since had to do similar things with other containers and programs). 

But to your main question - there were no plans for it, but I see no reason why not.  If you need it, I'm happy to look into it and turn this ticket into a feature request.

**Comment by java-javascript** [comment]
Awesome yeah - a feature request makes sense.   Thank you for setting it as such

**Comment by johrstrom** [comment]
I've created this branch `add-hostname-cfg` and the PR listed above. I tested it out quickly on `127.0.0.1`, `0.0.0.0` and my public ip and it all seemed to work just fine. Let me know if it works for you too and I'll pull it in and release it.

**Comment by java-javascript** [comment]
Works for me :).  Steps below.  Thanks!

# Cleaned and built
git checkout remotes/origin/add-hostname-cfg
mvn clean package -U

# Added the new version of the plugin (removed old versions)
cp target/jmeter-prometheus-plugin-0.6.0-SNAPSHOT.jar ~/jmeter/apache-jmeter-5.2/lib/ext/

# From JMeter Directory
bin/jmeter -Dprometheus.ip=<my ip>

# Prometheus call succeeds
curl http://<my ip>:9270/metrics

# Calls to other IPs fail as expected.

**Comment by SumantaSarathiChakraborty** [comment]
I was under the same need and this PR resolves it. I have checked it locally. Can we please have this  PR released to maven central, please.

**Comment by johrstrom** [comment]
Hi! I'm so sorry, of course I can release this tonight after work.

**Comment by SumantaSarathiChakraborty** [comment]
Thanks a lot. 

Also, just as I am very new to this plugin, do you have a sample jmx for http request and the plugin configuration (sample jmx provided is with the jsr. So wanted to quickly check with you!)

**Comment by johrstrom** [comment]
To the http question, no I didn't. I used jsr just because I didn't want to hit google or some other api.  But the listener configuration would be the same, other than the names of the metrics you're creating.

**Comment by johrstrom** [comment]
Thanks for the call to action. 0.6.0 is released to maven central and I even enabled a badge in the README so folks can just see what version we're working with.

Thanks all!
