### ISSUE TITLE
Not able to build the jar files

### ISSUE THREAD

**Issue by pkumarsingh** [johrstrom/jmeter-prometheus-plugin#71]
I am not able to build the jar files via Maven. Could someone build and upload the jar files here?

**Comment by johrstrom** [comment]
You can download off of maven central.  Directions are [here](https://github.com/johrstrom/jmeter-prometheus-plugin#web-browser).  Also you can download the jars off of the [releases](https://github.com/johrstrom/jmeter-prometheus-plugin/releases) tab here too.

**Comment by GiovanniPaoloGibilisco** [comment]
Hard to tell which is the actual error you are experiencing without a log. I tried and most likely the tricky part is signing the jar file without a private key. 
I've added a makefile to ease the building and testing phase without signing the jar file which should be fine for local development.
