### ISSUE TITLE
Sample Histogram Graph

### ISSUE THREAD

**Issue by QAInsights** [johrstrom/jmeter-prometheus-plugin#76]
I am trying to plot a histogram chart in Grafana for the response time where my buckets are 10,25,50,100,500. But the distribution of the graph is not right in Grafana. 

Could you please share the sample histogram graph settings for Grafana from JMeter prometheus metrics?

**Comment by johrstrom** [comment]
Hi! A fellow Ohioan!  I read your blog by the way, thought it was really good.

To your question, you should have a config something like this in your Listener.  The highlighted bit is where you can configure buckets. Please share what that listener entry looks like, and also what it is being returned in your `/metrics` API from Jmeter.  I want to be sure that what you have configured in Jmeter is correct and what it produces is correct. 

![image](https://user-images.githubusercontent.com/4874123/76432847-e745c480-6389-11ea-95c0-cb57bac1fb82.png)

**Comment by QAInsights** [comment]
Thanks @johrstrom :) Please stop by if you are planning to visit the in and around Maineville area :)

Below are my config and output. Is the grafana graph correct? Please clarify.

**JMeter Listener Config**
![image](https://user-images.githubusercontent.com/2826376/76482701-d7bb8f80-640c-11ea-9e19-8b5563e1bba9.png)

**JMeter Aggregate Report**
![image](https://user-images.githubusercontent.com/2826376/76482725-ea35c900-640c-11ea-9783-0b33449d35a5.png)

**Grafana Graph**

![image](https://user-images.githubusercontent.com/2826376/76482740-f6ba2180-640c-11ea-8366-bb7f3275a7ea.png)

**Comment by QAInsights** [comment]
Captured after few seconds

![image](https://user-images.githubusercontent.com/2826376/76482806-308b2800-640d-11ea-89cf-4b15b30cba9a.png)

**Comment by johrstrom** [comment]
That looks right to me.  I mean it looks like the plugin and grafana is working as expected. Grafana can only show what's in prometheus and promtheus can only hold what the plugin is showing. And it appears that that flow is working as expected.  Which is, your metrics API looks a lot like your grafana image.

Prometheus histograms are [cumulative](https://en.wikipedia.org/wiki/Histogram#Cumulative_histogram) so keep that in mind. You should just try tweaking those bucket sizes a bit to get a better visual. Maybe see what `50,70,90,150,300` looks like.  Or `50,60,70,80,90,100,300`. 

Or maybe even quantiles may be better for you.

**Comment by QAInsights** [comment]
Thanks for the clarification, let me try with different buckets :)

**Comment by vinnu-ssm** [comment]
Hi All  , 
Is there anyway we can get jmeter Aggregate report data in Grafana using Prometheus

Please let me if any dashboard or Prometheus query
