### ISSUE TITLE
Can it export the content of response body and response status code?

### ISSUE THREAD

**Issue by Germey** [johrstrom/jmeter-prometheus-plugin#79]
Because I'm using it in Grafana, but I find that I can not see the detail of response in Grafana when an error occurs. I want to see the respnose status code or response body in Grafana directly. I think I would be more convenient to track the error.

So I wonder if this plugin can export the content of response body and response status code to Prometheus?

**Comment by GiovanniPaoloGibilisco** [comment]
Hi Germey, 
Unfortunately, the integration can not export the response body as Prometheus deals only with timeseries. 
A few things you can try to get a better breakdown of errors are: 
 - add status check into prometheus and try to export them. You should know what to check a priori. 
 - use the `code` label already exported to look for specific http status code 

Moreover, if you want to dig into each specific error then Prometheus might not be the best choice as it is just a timeseries database. You might want to look directly to JMeter results or use some tracing tool on the application side (something like Loki)

**Comment by Germey** [comment]
Thanks very much for your detailed answer, I'll try it.

Best
