### ISSUE TITLE
Publish this plugin into JMeter-Plugins.org?

### ISSUE THREAD

**Issue by undera** [johrstrom/jmeter-prometheus-plugin#82]
Hi,
My question is simple: why not to publish this awesome plugin into jmeter-plugins.org repository? This way, a lot of users will know that this plugin exists.

**Comment by johrstrom** [comment]
Hi, thanks for the interest and sorry for the delay.

I'm not sure what that would entail or how to get started.

**Comment by undera** [comment]
To add your plugin into repository, you need to create a PR, where you add what we call "plugin descriptor" into one of repo JSON's. Usually it is "various.json" file.

In descriptor, you provide name, description, links to screenshot and documentation pages. There has to be a plugin page with documentation and a place to download plugin.

Download configuration is the most important section of descriptor. You specify a link to download plugin (and maybe some required libs) in "versions" items. Down the road, you'll be addin more items in "versions" when your plugin releases bugfixes.

For example, look at this one: https://github.com/undera/jmeter-plugins/pull/377

**Comment by undera** [comment]
I can help you start with initial plugin descriptor, which you can then modify as you like. Then, once you have a new release of your plugin, you need to create another PR with new version download links added (like others do, eg https://github.com/undera/jmeter-plugins/pull/407/files)

**Comment by GiovanniPaoloGibilisco** [comment]
I've created a pull request. Not sure about a couple of properties so I've remove them. Hope everything else is fine.

**Comment by undera** [comment]
That's a good start. I've commented there about couple of issues, please update PR with fixes and I'll merge it.

**Comment by GiovanniPaoloGibilisco** [comment]
I've added the missing pieces. 
@johrstrom I've added your nickname as "vendor" as you are the main contributor to this plugin. Hope this is fine with you, otherwise, let us know and we can change it in a successive pull request.

**Comment by johrstrom** [comment]
Yea thanks for taking care of this @GiovanniPaoloGibilisco.  You're welcome to add yourself to the vendor list too like a `;` separated email list.

**Comment by undera** [comment]
The PR is merged
