### ISSUE TITLE
Meassuring SuccessRatio not available in in drop down

### ISSUE THREAD

**Issue by vattna** [johrstrom/jmeter-prometheus-plugin#88]
Hello and thanks for the for the great work!

Using release 0.6.0 with jMeter 5.3, i can't find SuccessRatio as measurement:
![image](https://user-images.githubusercontent.com/9417522/92460395-9ac03200-f1d0-11ea-8365-833ddf4bbde5.png)

manualy modifying .jmx file works:
```
# HELP test_successRatio_success default help string
# TYPE test_successRatio_success counter
test_successRatio_success{label="identify - username / pass",} 9.0
....
```
but option is still not available in gui afterwards

**Comment by johrstrom** [comment]
Thanks for the ticket! That seems to be a bug. I'll take a look at it this week when I get a chance.

**Comment by GiovanniPaoloGibilisco** [comment]
Testing on 0.6.0 I see SuccessRatio can be selected from the drop-down (it just does not appear in the list as it's too long and you need to scroll down).
Can you verify if it's there or not?
![image](https://user-images.githubusercontent.com/5967863/94557452-db0a5180-025e-11eb-8df8-ee130661f6a5.png)

**Comment by vattna** [comment]
> Testing on 0.6.0 I see SuccessRatio can be selected from the drop-down (it just does not appear in the list as it's too long and you need to scroll down).
> Can you verify if it's there or not?
> ![image](https://user-images.githubusercontent.com/5967863/94557452-db0a5180-025e-11eb-8df8-ee130661f6a5.png)

Hah, this is actually it, I can see the scroll bar in my attached screenshot as well.

I'll just blame it on jMeter not being very optimized for 4k resolution and not having a thought of a scroll bar appearing on such a short list.
