### ISSUE TITLE
Overriding properties - different servers for Prometheus and JMeter

### ISSUE THREAD

**Issue by PHewera** [johrstrom/jmeter-prometheus-plugin#91]
Hey everyone,
i am bit a bit confused about overriding the properties for the listener. Maybe anyone can help me out :)

Situation: Prometheus runs on server A, JMeter runs on server B

I tried to override the listener properties in JMeter by including a custom user.properties file which looks like the following:
```
prometheus.ip=ip_server_a
prometheus.port=9270
```
The user.properties file is working, because i already had some properties in there which are loaded.

My prometheus job config:
```
  - job_name: 'jmeter'
    static_configs:
    - targets: ['localhost:9270']
```
When Prometheus and JMeter are running on the same server everything works fine. Did i miss anything?

**Comment by johrstrom** [comment]
Hi! Everything should point to `ip_server_b` which runs Jmeter.

```
prometheus.ip=ip_server_b
prometheus.port=9270
```

```yaml
- job_name: 'jmeter'
    static_configs:
    - targets: ['ip_server_b:9270']
```

**Comment by PHewera** [comment]
Hey, thanks!
Already figured it out, got a little confused yesterday.
