### ISSUE TITLE
Update README to detail how to use properties

### ISSUE THREAD

**Issue by mcruzvas** [johrstrom/jmeter-prometheus-plugin#97]
Is it inside the jmx file? Where ? Inside user defined variables doesnt do it  
Thanks for this great tool

**Comment by chiabre** [comment]
You can define the exporter properties as standard JMeter inline arguments. 

For the port, it would be 

-Jprometheus.port=9270

**Comment by johrstrom** [comment]
Yep! Thanks @chiabre! 

For reference, here are all the options you can override https://github.com/johrstrom/jmeter-prometheus-plugin#properties-you-can-override either through the CLI through `-J` or in a properties file of your choice.

**Comment by johrstrom** [comment]
Actually, let me re-open this and use it to update the docs. So that portion of the documentation should indicate how to use these properties, maybe linking back to jmeter docs.
